spring:
  application:
    name: crud-project

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 2525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 7000