### GET request to fetch all employees
GET http://localhost:7000/api/v1/employees


### POST request to add a new employee
POST localhost:7000/api/v1/employees
Content-Type: application/json

{
         "firstName": "ebube",
         "lastName": "ugwu",
         "email": "ebube@email.com",
         "department": "IT",
         "salary": 20000,

         "active": true
         }
